  export const collegeProducts = [
    {
      sku: "c1",
      image: "/assets/images/category-youth-C4gUNjqm.jpg",
      price: "12,000",
      label: "Dress",
      stock: 10,
      description: "A stylish dress perfect for college events.",
      reviews: [
        { user: "Alice", comment: "Loved the fabric!", rating: 5 },
        { user: "Malaika", comment: "Fits perfectly.", rating: 4 },
      ],
    },
    {
      sku: "c2",
      image: "/assets/images/category-youth-C4gUNjqm.jpg",
      price: "22,000",
      label: "Casual Outfit",
      stock: 15,
      description: "Comfortable casual outfit for everyday wear.",
      reviews: [],
    },
    {
      sku: "c3",
      image: "/assets/images/category-youth-C4gUNjqm.jpg",
      price: "19,000",
      label: "Summer Dress",
      stock: 8,
      description: "Light and breezy summer dress for warm days.",
      reviews: [],
    },
    {
      sku: "c4",
      image: "/assets/images/category-youth-C4gUNjqm.jpg",
      price: "25,000",
      label: "Chic Top",
      stock: 20,
      description: "Trendy top to pair with your favorite jeans.",
      reviews: [],
    },
    {
      sku: "c1",
      image: "/assets/images/category-youth-C4gUNjqm.jpg",
      price: "12,000",
      label: "Dress",
      stock: 10,
      description: "A stylish dress perfect for college events.",
      reviews: [],
    },
    {
      sku: "c2",
      image: "/assets/images/category-youth-C4gUNjqm.jpg",
      price: "22,000",
      label: "Casual Outfit",
      stock: 15,
      description: "Comfortable casual outfit for everyday wear.",
      reviews: [],
    },
    {
      sku: "c3",
      image: "/assets/images/category-youth-C4gUNjqm.jpg",
      price: "19,000",
      label: "Summer Dress",
      stock: 8,
      description: "Light and breezy summer dress for warm days.",
      reviews: [],
    },
    {
      sku: "c4",
      image: "/assets/images/category-youth-C4gUNjqm.jpg",
      price: "25,000",
      label: "Chic Top",
      stock: 20,
      description: "Trendy top to pair with your favorite jeans.",
      reviews: [],
    },
  ];

  export const workingWomen = [
    {
      sku: "w1",
      image: "/assets/images/bernd-dittrich-HvLvBLfHdgs-unsplash.jpg",
      price: "45,000",
      label: "Formal Suit",
      stock: 5,
      description: "Professional formal suit for business meetings.",
      reviews: [],
    },
    {
      sku: "w2",
      image: "/assets/images/bernd-dittrich-HvLvBLfHdgs-unsplash.jpg",
      price: "22,000",
      label: "Office Wear",
      stock: 12,
      description: "Comfortable and stylish office wear.",
      reviews: [],
    },
    {
      sku: "w3",
      image: "/assets/images/bernd-dittrich-HvLvBLfHdgs-unsplash.jpg",
      price: "32,000",
      label: "Blouse Set",
      stock: 7,
      description: "Elegant blouse set for work and meetings.",
      reviews: [],
    },
    {
      sku: "w4",
      image: "/assets/images/bernd-dittrich-HvLvBLfHdgs-unsplash.jpg",
      price: "40,000",
      label: "Work Dress",
      stock: 9,
      description: "Chic work dress suitable for all-day wear.",
      reviews: [],
    },
    {
      sku: "w1",
      image: "/assets/images/bernd-dittrich-HvLvBLfHdgs-unsplash.jpg",
      price: "45,000",
      label: "Formal Suit",
      stock: 5,
      description: "Professional formal suit for business meetings.",
      reviews: [],
    },
    {
      sku: "w2",
      image: "/assets/images/bernd-dittrich-HvLvBLfHdgs-unsplash.jpg",
      price: "22,000",
      label: "Office Wear",
      stock: 12,
      description: "Comfortable and stylish office wear.",
      reviews: [],
    },
    {
      sku: "w3",
      image: "/assets/images/bernd-dittrich-HvLvBLfHdgs-unsplash.jpg",
      price: "32,000",
      label: "Blouse Set",
      stock: 7,
      description: "Elegant blouse set for work and meetings.",
      reviews: [],
    },
    {
      sku: "w4",
      image: "/assets/images/bernd-dittrich-HvLvBLfHdgs-unsplash.jpg",
      price: "40,000",
      label: "Work Dress",
      stock: 9,
      description: "Chic work dress suitable for all-day wear.",
      reviews: [],
    },
  ];

  export const matureWomen = [
    {
      sku: "m1",
      image: "/assets/images/category-women-CwbBwS-K.jpg",
      price: "17,000",
      label: "Elegant Dress",
      stock: 6,
      description: "Sophisticated dress for mature women.",
      reviews: [],
    },
    {
      sku: "m2",
      image: "/assets/images/category-women-CwbBwS-K.jpg",
      price: "15,000",
      label: "Cultural Dress",
      stock: 14,
      description: "Beautiful cultural dress for special occasions.",
      reviews: [],
    },
    {
      sku: "m3",
      image: "/assets/images/category-women-CwbBwS-K.jpg",
      price: "32,000",
      label: "Traditional Set",
      stock: 4,
      description: "Traditional attire with a modern touch.",
      reviews: [],
    },
    {
      sku: "m4",
      image: "/assets/images/category-women-CwbBwS-K.jpg",
      price: "28,000",
      label: "African Print",
      stock: 11,
      description: "Vibrant African print outfit for all occasions.",
      reviews: [],
    },
    {
      sku: "m1",
      image: "/assets/images/category-women-CwbBwS-K.jpg",
      price: "17,000",
      label: "Elegant Dress",
      stock: 6,
      description: "Sophisticated dress for mature women.",
      reviews: [],
    },
    {
      sku: "m2",
      image: "/assets/images/category-women-CwbBwS-K.jpg",
      price: "15,000",
      label: "Cultural Dress",
      stock: 14,
      description: "Beautiful cultural dress for special occasions.",
      reviews: [],
    },
    {
      sku: "m3",
      image: "/assets/images/category-women-CwbBwS-K.jpg",
      price: "32,000",
      label: "Traditional Set",
      stock: 4,
      description: "Traditional attire with a modern touch.",
      reviews: [],
    },
    {
      sku: "m4",
      image: "/assets/images/category-women-CwbBwS-K.jpg",
      price: "28,000",
      label: "African Print",
      stock: 11,
      description: "Vibrant African print outfit for all occasions.",
      reviews: [],
    },
  ];
  
  export const allProducts = [
    ...collegeProducts,
    ...workingWomen,
    ...matureWomen,
  ];